name: VC Sourcing (Daily)

on:
  schedule:
    - cron: "30 14 * * *"   # ~08:30 America/Costa_Rica in UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Write service account JSON
        run: |
          printf "%s" "${{ secrets.GCP_SA_JSON_BASE64 }}" | base64 -d > service_account.json
      - name: Run sourcing job
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          TZ: ${{ secrets.TZ }}
        run: |
          python src/sourcing.py
